# Site settings
site: Dea Afrizal Blog
title: Dea Afrizal Programmer Youtuber Blog
keywords: dea afrizal, dea afrizal blog, blog programmer, artikel programmer, web developer indonesia, youtuber programmer indonesia
description: >-
  Dea Afrizal Blog
lang: id-ID
timezone: Asia/Jakarta
repo: https://blog.deaafrizal.com/ # site repo [optional]
google_verify: XXX # Put your Google Verification here
google_analytics: 35484031 # Put your Google Analytics code
discus-identifier: XXX

# Author settings
author:
  name: Dea Afrizal
  bio: Tech Enthusiast - Coba Dulu, Jagonya Belakangan
  picture: assets/images/dealog.png
  github: deaaprizal # github username
  twitter: # twitter username
  facebook: # facebook username
  instagram: dea.afrizal # instagram username
  youtube: https://youtube.com/@deaafrizal # youtube username
  linkedin: # linkedin username
  email: deacode@icloud.com # email adress

# URL settings
url: "https://blog.deaafrizal.com/" # Domain Name of host. [username].github.io for github pages
permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
paginate: 20
paginate_path: "/page/:num"

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:path

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled: true
  collections: false
